name: Playwright Base Tests
 
on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight UTC
  workflow_dispatch:
 
jobs:
  playwright-tests:
    name: 🧪 Playwright Tests
    runs-on: ubuntu-latest

    env:
      BUTestPassword: ${{ secrets.BUTESTPASSWORD }}
      BUPasscode: ${{ secrets.BUPASSCODE }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
 
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
 
      - name: 📦 Install Dependencies
        run: npm install        
 
      - name: 🎭 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 📝 Create .env file
        run: |
          echo "BUTestPassword=${{ secrets.BUTESTPASSWORD }}" >> .env
          echo "BUPasscode=${{ secrets.BUPASSCODE }}" >> .env
          echo "SF_USERNAME=${{ secrets.SF_USERNAME }}" >> .env
          echo "SF_CLIENT_ID=${{ secrets.SF_CLIENT_ID }}" >> .env

      - name: 🔑 Create server.key file
        run: echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
 
      - name: 🧪 Run Playwright Tests
        run: npx playwright test --project=chromium      
 
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
